In [15]:
var_1 = 10
var_2 =15.48
var_3 ="python"
var_4 = True
print(type(var_1))
print(type(var_2))
print(type(var_3))
print(type(var_4))

b = "25"
print(int(b))

x = 3.75
print(int(x))

str(10)

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
25
3

'10'

In [16]:
a,b = 3,4
a,b = b,a
print(a,b)

x =3+4j
print(type(x))

x,y,z = 8,3,6
print(x,y,z)

a,b,c = 3,3,3
print(a,b,c)

f = 0
print(bool(f))

4 3
<class 'complex'>
8 3 6
3 3 3
False

In [26]:
name = "Manju"
age = 25
city = "Bangalore"
print(name)
print(age)
print(city)

a = 6
print(float(a))
f = 4.78
print(type(f))
f_name =input("f_name:")
l_name =input("l_name:")
print(f_name, l_name)

Manju
25
Bangalore
6.0
<class 'float'>
Manju K

In [20]:
name =input("Enter the name:")
print("Hello",name)

a = 40
b = 70
age = int(input("Enter age:"))
print("age:",age)
sum = a+b
print("Sum:",sum)

Hello Manju
age: 25
Sum: 110

In [44]:
x = "python programming"
print(x[0])
print(x[-1])
print(x[0:5:1])
print(x[-4:])
print(x.upper())
print(x.replace("p","P"))
print(x.count("n"))

p
g
pytho
ming
PYTHON PROGRAMMING
Python Programming
2

In [46]:
name = input("name:")
age = int(input("age:"))
city = input("city:")
print(f"Hello {name}!")
print(f"You are {age} years old and you live in {city}.")

Hello Rahul!
You are 22 years old and you live in Chennai.

In [2]:
a = 15
b = 4
print("a+b:", a+b)
print("a-b:", a-b)
print("a*b:", a*b)
print("a/b:", a/b)
print("a//b:", a//b)
print("a%b:", a%b)
print("a**b:", a**b)

a+b: 19
a-b: 11
a*b: 60
a/b: 3.75
a//b: 3
a%b: 3
a**b: 50625

In [4]:
print(25>10)
print(8<3)
print(f"{25>10} and {8<3}")
print("e" in "elephant")
a = 15
b = 8
print(a>b and b>a)
print(a<b or a>b)
print(a!=b)
print("a%b:",125%9)
print("a//b:",(12+8)//5)

True
False
True and False
True
False
True
True
a%b: 8
a//b: 4

In [20]:
x =(1,2,3,4,5,8)
print(x)
print(x[2])
print(x[0:3:1])
print(x.count(5))
print(x[4])
y = (1,2,3,4)
z = (5,6,7,8)
print(y+z)

(1, 2, 3, 4, 5, 8)
3
(1, 2, 3)
1
5
(1, 2, 3, 4, 5, 6, 7, 8)

In [2]:
x = 8
y = 12
print("x==y:", x==y)
print("x!=y:", x!=y)
print("x>y:", x>y)
print("x<y:", x<y)
print("x>=y:", x>=y)
print("x<=y:", x<=y)

x==y: False
x!=y: True
x>y: False
x<y: True
x>=y: False
x<=y: True

In [7]:
num_1 = [1,2,3,4]
num_2 = [1,2,3,4]
num_2 = num_1
print(num_1 is num_2)
print(num_1 is not num_2)

True
False

In [32]:
fruits =["Apple","Mango","Kiwi","Pine","Orange"]
print(fruits)
print(fruits[0])
print(fruits[-1])
print(fruits[1:4])
print(fruits[-1::-1])
fruits[1] = "carrot"
print(fruits)
fruits.append("Grapes")
print(fruits)
fruits.insert(2,"Banana")
print(fruits)
fruits.remove("Kiwi")
print(fruits)
print(fruits.index("Apple"))

['Apple', 'Mango', 'Kiwi', 'Pine', 'Orange']
Apple
Orange
['Mango', 'Kiwi', 'Pine']
['Orange', 'Pine', 'Kiwi', 'Mango', 'Apple']
['Apple', 'carrot', 'Kiwi', 'Pine', 'Orange']
['Apple', 'carrot', 'Kiwi', 'Pine', 'Orange', 'Grapes']
['Apple', 'carrot', 'Banana', 'Kiwi', 'Pine', 'Orange', 'Grapes']
['Apple', 'carrot', 'Banana', 'Pine', 'Orange', 'Grapes']
0

In [10]:
product_name = input("Enter the product:")
price = float(input("Enter price:"))
print("Enter product:", product_name)
print("Enter price:", price)
print(f"Rounded price: {round(price,1)}")
print(f"Formatted price: {price:.2f}")

Enter product: Sugar
Enter price: 249.571
Rounded price: 249.6
Formatted price: 249.57

In [4]:
numbers = [1,3,5,7,8,9,11]
for num in numbers:
    if num%2 != 0:
        print(num)
    else:
        break

1
3
5
7

In [10]:
name = "python"
vowels = "aeiou"
for x in name:
    if x in vowels:
        break
    else:
        print(x)

p
y
t
h

In [13]:
for i in range(0,7):
   if i ==5:
      continue
   else:
      print(i)

0
1
2
3
4
6

In [9]:
arr = [10,15,20,25,30,35]
target = 25
i=0
while i < len(arr):
    if arr[i] == 25:
        print(f"found {target} in index {i} ")
        break
    i+=1
else:
    print("not found")

found 25 in index 3

In [10]:
num =[10,20,-4,30,-5]
for i in num:
    if i<0:
        continue
    else:
        print(i)

10
20
30

In [17]:
number =[10,20,-4,30,-5]
i=0

while i <len(number):
    if number [i]<0:
       i+=1
       continue
    
    print(number[i])
    i+=1

10
20
30

In [19]:
i = 1
while i <=20:
    if i%2==0:
        print(i)
    i+=1

2
4
6
8
10
12
14
16
18
20

In [3]:
for i in range(1,51):
    if i%7==0:
        print(i)

7
14
21
28
35
42
49

In [4]:
n = int(input())
for i in range(1,11):
    print(f"{n}*{i}={n*i}")

7*1=7
7*2=14
7*3=21
7*4=28
7*5=35
7*6=42
7*7=49
7*8=56
7*9=63
7*10=70

In [7]:
marks = [78, 92, 45, 88, 61, 39, 95]
for i in marks:
    if i>=75:
        print(i)

78
92
88
95

In [11]:
words = ["sky", "apple", "rhythm", "orange", "fly"]
for i,word in enumerate(words):
    if 'a' in word or 'i' in word or 'o'in word or 'e' in word or 'u' in word:
        print(i,word)

1 apple
3 orange

In [13]:
employees = {
    "Alice": 65000,
    "Bob": 48000,
    "Charlie": 72000,
    "David": 51000
}
for name,salary in employees.items():
    if salary>50000:
        print(name)

Alice
Charlie
David

In [17]:
products = {
    "Laptop": 65000,
    "Mouse": 799,
    "Keyboard": 1499,
    "Monitor": 12000
}
for product,price in products.items():
    print(f"{product} costs ₹{price}")

temperatures = [32.4567, 28.1294, 35.9876, 30.5]
for tem in temperatures:
    print(f"{tem:.2f}c")

Laptop costs ₹65000
Mouse costs ₹799
Keyboard costs ₹1499
Monitor costs ₹12000
32.46c
28.13c
35.99c
30.50c

In [21]:
numbers = [14, 27, 18, 35, 40, 51]
for i in range(len(numbers)):
    if numbers[i]%2==0:
        print(f"{i}->{numbers[i]}")

0->14
2->18
4->40

In [26]:
students = {
    "John": {"Python": 85, "SQL": 78},
    "Sara": {"Python": 92, "SQL": 88},
    "David": {"Python": 65, "SQL": 72}
}
for name,mark in students.items():
    if mark["Python"] >=80:
        print(f'{name} scored {mark['Python']} in python')

John scored 85 in python
Sara scored 92 in python

In [7]:
def calculations(a,b):
    def add():
      return  a+b
    def sub():
      return a-b
    return add(), sub()
calculations (10,5)

(15, 5)

In [12]:
file = open('marks.txt','r')
print("enter mark:",file.read())

enter mark: 75
80
90
85
95

In [8]:
file = open('marks.txt','r')
print("Number of students:",len(file.readlines()))
file.close()

Number of students: 5

In [13]:
file = open('marks.txt','r')
result = file.readlines()
total = 0
for i in result:
    total+= int(i)
print("total:",total)
file.close()

total: 425

In [3]:
def check_even_odd(number):
    if number % 2 == 0:
        return "Even"
    else:
        return "Odd"

print(check_even_odd(2))
print(check_even_odd(3))
print(check_even_odd(4))

Even
Odd
Even

In [9]:
def greet(name,message="welcome to python"):
    return(name,message)
greet('Manju',message='Good morning!')
name,message = greet('Manju',message='Good morning!')
print(name,message)

Manju Good morning!

In [1]:
def number_summary(*numbers):
    total = sum(numbers)
    count = len(numbers)
    average = total/count
    return total,count,average
total,count,average = number_summary(10,20,30,40,50)
print("total:", total)
print("count:", count)
print("average:", average)

total: 150
count: 5
average: 30.0

In [ ]:
file = open('students.txt', 'x')
file.write('kishore\n')
file.write('sudha\n')
file.write('kannan\n')
file.write('Ram\n')
file.write('sweetha\n')
file.close()

In [3]:
file = open('students.txt','r')
print(file.read())
file = open('students.txt','r')
print(file.readlines())

kishore
sudha
kannan
Ram
sweetha

['kishore\n', 'sudha\n', 'kannan\n', 'Ram\n', 'sweetha\n']

In [22]:
def check_password(password):
    length = False
    digit = False
    uppercase = False
    if len(password)>=8:
        length = True
    for i in password:
        if i.isdigit():
            digit = True
        elif i.isupper():
            uppercase = True
    if length and digit and uppercase:
        return True
    else:
        return False
print(check_password("manju7"))
print(check_password("Manju1234"))

False
True

In [27]:
def calculate_bill(items, discount=0):
    sub_total = sum(items)
    total = sub_total-(sub_total*discount/100)
    return total
items = [500, 250, 100, 150]
print(calculate_bill(items,10))

900.0

In [2]:
my_list = [i for i in range(1,5)]
my_list

[1, 2, 3, 4]

In [2]:
text = "python programming"
[i for i in text if i in "aeiou" ]

['o', 'o', 'a', 'i']

In [13]:
maximum = lambda a,b:max(a,b)
print(maximum(100,105))

105

In [47]:
arr=[32,67,21,34,2,3]
# sorted_arr=lambda arr: arr.sort()
# print(sorted_arr(arr))

def sortArr(lst):
    lst.sort()
    # print(lst1)
    
print(sortArr(arr))
print(arr)

None
[2, 3, 21, 32, 34, 67]

In [27]:
prices = [100, 200, 300, 400]
tax = 1.18
list(map(lambda price: price+tax, prices))

[101.18, 201.18, 301.18, 401.18]

In [30]:
students = [
    ("Arun", 85),
    ("Priya", 35),
    ("Rahul", 72),
    ("Meena", 28),
    ("Vijay", 90)
]
list(filter(lambda num:num[1]>=60,students))

[('Arun', 85), ('Rahul', 72), ('Vijay', 90)]

In [31]:
numbers = [12, 5, 18, 7, 20, 3, 25]
list(filter(lambda x:x>10,numbers))

[12, 18, 20, 25]

In [33]:
square = (i**2 for i in range(1,100))
print(next(square))
print(next(square))
print(next(square))
print(next(square))
print(next(square))

1
4
9
16
25

In [36]:
with open('mark.txt','w')as f:
    f.write("35\n78\n92\n45\n28\n67\n81\n39\n")

In [13]:
with open('mark.txt','r')as f:
    result = f.readlines()
    print(result)
result = list(map(int,result))
print(result)
passed = list(i for i in result if i>35)
print(passed)
topper = list(i for i in passed if i>80)
print(topper)
list(map(lambda i:i+5,result))
at_least = list(filter(lambda i:i>=50,result))
print(at_least)
square = (i**2 for i in result)
print(next(square))
for i in square:
    print(i)

['35\n', '78\n', '92\n', '45\n', '28\n', '67\n', '81\n', '39\n']
[35, 78, 92, 45, 28, 67, 81, 39]
[78, 92, 45, 67, 81, 39]
[92, 81]
[78, 92, 67, 81]
1225
6084
8464
2025
784
4489
6561
1521

In [ ]:
class Student:   
    def __init__( self,name, age):
        self.name = name
        self.age = age
    def printName(self):


student1 = Student("Arun", 20)
student2 = Student("Karthik",24)

print(student1.name)
print(student1.age)
print(student2.name)
print(student2.age)

Karthik
24

In [19]:
class operations:

     def __init__(self, word):
         self.word = word

     def upper(self):
        return self.word.upper()

     def length(self, value):
        return len(self.word) + value

sample = operations("hello")
up=sample.upper()
l=sample.length(5)
print(up,l)

HELLO 10

In [35]:
class bank_account:
    def __init__(self,name,balance):
        self.name = name
        self.balance = balance
    def deposit(self,value):
        self.balance+=value
        print("deposited successfully")
    def display(self):
        print(self.name,self.balance)
    def credit(self,value):
        self.balance-=value
        print("credited successfully")
customer1 = bank_account("Ajay",50000)
customer2 = bank_account("Divya",30000)
customer1.deposit(10000)
customer1.display()
customer2.display()
customer1.credit(5000)
customer1.display()

deposited successfully
Ajay 60000
Divya 30000
credited successfully
Ajay 55000

In [ ]:
API_KEY = "Oz6JAz3T8uMrfeWt5cb3fQKfRfyMKHCB9BHaBFQl"
url = f"https://api.nasa.gov/neo/rest/v1/feed?start_date={start_date}&end_date={end_date}&api_key={api_key}"

In [12]:
class Student:
    def __init__(self,name,marks):
        self.name = name
        self.marks = marks
    def __str__(self):
        return f"{self.name} scored {self.marks} marks"
s1 = Student("Aravind",88)
print(s1)

Aravind scored 88 marks

In [1]:
class Employee: # parent
    def __init__(self, name, salary):
         self.name = name
         self.salary = salary

    def get_info(self):
      return f'{self.name} earns {self.salary}'

class Manager(Employee):
     def __init__(self,name,salary, teamsize):
          super().__init__(name,salary)
          self.teamsize = teamsize

     def complete_info(self):
          basic_info = self.get_info()  # extending the parent method instead of repeating the codes
          return f'{basic_info}, he manages a team of size {self.teamsize}'


emp = Manager("arun", 80000, 10)
emp.complete_info()

'arun earns 80000, he manages a team of size 10'

In [2]:
class A:
  def __init__(self):
      print("This is A's constructor")

  def method_A(self):
      print("I am from method A")

class B:
  def __init__(self):
      print("This is B's constructor")

  def method_B(self):
      print("I am from method B")

class C(A,B): # it will inherit based on order
    def __init__(self):
      A.__init__(self)
      B.__init__(self)
      print("I inherit from both A,B")




c = C()
c

This is A's constructor
This is B's constructor
I inherit from both A,B

In [ ]:
API_KEY = "s4R5sbtXMJtr68tnL8U9a4CszFapSMReUniEB7Wo"

In [3]:
import requests
start_date = "2024-01-01"
end_date = "2024-01-03"
api_key = "s4R5sbtXMJtr68tnL8U9a4CszFapSMReUniEB7Wo"
url = f"https://api.nasa.gov/neo/rest/v1/feed?start_date={start_date}&end_date={end_date}&api_key={api_key}"
response = requests.get(url)
response.json()

{'links': {'next': 'http://api.nasa.gov/neo/rest/v1/feed?start_date=2024-01-03&end_date=2024-01-05&detailed=false&api_key=s4R5sbtXMJtr68tnL8U9a4CszFapSMReUniEB7Wo',
  'previous': 'http://api.nasa.gov/neo/rest/v1/feed?start_date=2023-12-30&end_date=2024-01-01&detailed=false&api_key=s4R5sbtXMJtr68tnL8U9a4CszFapSMReUniEB7Wo',
  'self': 'http://api.nasa.gov/neo/rest/v1/feed?start_date=2024-01-01&end_date=2024-01-03&detailed=false&api_key=s4R5sbtXMJtr68tnL8U9a4CszFapSMReUniEB7Wo'},
 'element_count': 25,
 'near_earth_objects': {'2024-01-02': [{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2415949?api_key=s4R5sbtXMJtr68tnL8U9a4CszFapSMReUniEB7Wo'},
    'id': '2415949',
    'neo_reference_id': '2415949',
    'name': '415949 (2001 XY10)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2415949',
    'absolute_magnitude_h': 19.37,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.3552670883,
      'estimated_diameter_max': 0.7944013596},
     'meters': {'estimated_diameter_min': 355.267088298,
      'estimated_diameter_max': 794.4013596028},
     'miles': {'estimated_diameter_min': 0.2207526659,
      'estimated_diameter_max': 0.4936179672},
     'feet': {'estimated_diameter_min': 1165.5744739718,
      'estimated_diameter_max': 2606.3037566394}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 13:14',
      'epoch_date_close_approach': 1704201240000,
      'relative_velocity': {'kilometers_per_second': '15.8905264223',
       'kilometers_per_hour': '57205.8951204341',
       'miles_per_hour': '35545.5185541386'},
      'miss_distance': {'astronomical': '0.3372535274',
       'lunar': '131.1916221586',
       'kilometers': '50452409.349026638',
       'miles': '31349673.4658100844'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3160747?api_key=s4R5sbtXMJtr68tnL8U9a4CszFapSMReUniEB7Wo'},
    'id': '3160747',
    'neo_reference_id': '3160747',
    'name': '(2003 SR84)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3160747',
    'absolute_magnitude_h': 26.0,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0167708462,
      'estimated_diameter_max': 0.0375007522},
     'meters': {'estimated_diameter_min': 16.7708462163,
      'estimated_diameter_max': 37.5007521798},
     'miles': {'estimated_diameter_min': 0.0104209175,
      'estimated_diameter_max': 0.0233018799},
     'feet': {'estimated_diameter_min': 55.0224631002,
      'estimated_diameter_max': 123.0339677816}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 22:45',
      'epoch_date_close_approach': 1704235500000,
      'relative_velocity': {'kilometers_per_second': '10.7191818981',
       'kilometers_per_hour': '38589.054833182',
       'miles_per_hour': '23977.7379878735'},
      'miss_distance': {'astronomical': '0.1323425924',
       'lunar': '51.4812684436',
       'kilometers': '19798169.933318188',
       'miles': '12302012.3446714744'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3309828?api_key=s4R5sbtXMJtr68tnL8U9a4CszFapSMReUniEB7Wo'},
    'id': '3309828',
    'neo_reference_id': '3309828',
    'name': '(2005 YQ96)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3309828',
    'absolute_magnitude_h': 20.62,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1997813652,
      'estimated_diameter_max': 0.4467247133},
     'meters': {'estimated_diameter_min': 199.78136523,
      'estimated_diameter_max': 446.7247132921},
     'miles': {'estimated_diameter_min': 0.1241383467,
      'estimated_diameter_max': 0.2775817818},
     'feet': {'estimated_diameter_min': 655.4506943013,
      'estimated_diameter_max': 1465.6323083572}},
    'is_potentially_hazardous_asteroid': True,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 19:42',
      'epoch_date_close_approach': 1704224520000,
      'relative_velocity': {'kilometers_per_second': '15.6702817644',
       'kilometers_per_hour': '56413.0143519451',
       'miles_per_hour': '35052.8532788517'},
      'miss_distance': {'astronomical': '0.1670126223',
       'lunar': '64.9679100747',
       'kilometers': '24984732.559194501',
       'miles': '15524792.9180700738'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3457842?api_key=s4R5sbtXMJtr68tnL8U9a4CszFapSMReUniEB7Wo'},
    'id': '3457842',
    'neo_reference_id': '3457842',
    'name': '(2009 HC21)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3457842',
    'absolute_magnitude_h': 22.1,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1010543415,
      'estimated_diameter_max': 0.2259643771},
     'meters': {'estimated_diameter_min': 101.054341542,
      'estimated_diameter_max': 225.9643771094},
     'miles': {'estimated_diameter_min': 0.0627922373,
      'estimated_diameter_max': 0.140407711},
     'feet': {'estimated_diameter_min': 331.5431259047,
      'estimated_diameter_max': 741.3529669956}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 12:06',
      'epoch_date_close_approach': 1704197160000,
      'relative_velocity': {'kilometers_per_second': '6.0808661718',
       'kilometers_per_hour': '21891.1182185894',
       'miles_per_hour': '13602.2895397674'},
      'miss_distance': {'astronomical': '0.4920511029',
       'lunar': '191.4078790281',
       'kilometers': '73609796.924990823',
       'miles': '45739006.8632584374'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3553062?api_key=s4R5sbtXMJtr68tnL8U9a4CszFapSMReUniEB7Wo'},
    'id': '3553062',
    'neo_reference_id': '3553062',
    'name': '(2010 XA11)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3553062',
    'absolute_magnitude_h': 26.1,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0160160338,
      'estimated_diameter_max': 0.0358129403},
     'meters': {'estimated_diameter_min': 16.0160337979,
      'estimated_diameter_max': 35.8129403019},
     'miles': {'estimated_diameter_min': 0.0099518989,
      'estimated_diameter_max': 0.0222531225},
     'feet': {'estimated_diameter_min': 52.5460443254,
      'estimated_diameter_max': 117.4965270602}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 15:31',
      'epoch_date_close_approach': 1704209460000,
      'relative_velocity': {'kilometers_per_second': '8.7413828775',
       'kilometers_per_hour': '31468.9783588978',
       'miles_per_hour': '19553.5993586163'},
      'miss_distance': {'astronomical': '0.2358022486',
       'lunar': '91.7270747054',
       'kilometers': '35275514.131770482',
       'miles': '21919188.0752253716'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3591616?api_key=s4R5sbtXMJtr68tnL8U9a4CszFapSMReUniEB7Wo'},
    'id': '3591616',
    'neo_reference_id': '3591616',
    'name': '(2011 YP10)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3591616',
    'absolute_magnitude_h': 23.94,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0433066885,
      'estimated_diameter_max': 0.0968366995},
     'meters': {'estimated_diameter_min': 43.3066885476,
      'estimated_diameter_max': 96.8366994728},
     'miles': {'estimated_diameter_min': 0.0269095204,
      'estimated_diameter_max': 0.0601715168},
     'feet': {'estimated_diameter_min': 142.0823160544,
      'estimated_diameter_max': 317.7057170982}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 12:59',
      'epoch_date_close_approach': 1704200340000,
      'relative_velocity': {'kilometers_per_second': '5.8070023218',
       'kilometers_per_hour': '20905.2083584121',
       'miles_per_hour': '12989.6834935922'},
      'miss_distance': {'astronomical': '0.0704899554',
       'lunar': '27.4205926506',
       'kilometers': '10545147.184234998',
       'miles': '6552450.6191110524'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3608936?api_key=s4R5sbtXMJtr68tnL8U9a4CszFapSMReUniEB7Wo'},
    'id': '3608936',
    'neo_reference_id': '3608936',
    'name': '(2012 SD22)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3608936',
    'absolute_magnitude_h': 20.05,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.2597496533,
      'estimated_diameter_max': 0.580817882},
     'meters': {'estimated_diameter_min': 259.7496533301,
      'estimated_diameter_max': 580.817881978},
     'miles': {'estimated_diameter_min': 0.1614009018,
      'estimated_diameter_max': 0.3609033881},
     'feet': {'estimated_diameter_min': 852.1970526314,
      'estimated_diameter_max': 1905.5705399087}},
    'is_potentially_hazardous_asteroid': True,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 13:50',
      'epoch_date_close_approach': 1704203400000,
      'relative_velocity': {'kilometers_per_second': '11.0227943004',
       'kilometers_per_hour': '39682.059481597',
       'miles_per_hour': '24656.8885706623'},
      'miss_distance': {'astronomical': '0.1644228854',
       'lunar': '63.9605024206',
       'kilometers': '24597313.435094098',
       'miles': '15284061.8372026324'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3795154?api_key=s4R5sbtXMJtr68tnL8U9a4CszFapSMReUniEB7Wo'},
    'id': '3795154',
    'neo_reference_id': '3795154',
    'name': '(2017 YD8)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3795154',
    'absolute_magnitude_h': 21.87,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1123453177,
      'estimated_diameter_max': 0.2512117673},
     'meters': {'estimated_diameter_min': 112.3453176718,
      'estimated_diameter_max': 251.2117672679},
     'miles': {'estimated_diameter_min': 0.0698081224,
      'estimated_diameter_max': 0.156095707},
     'feet': {'estimated_diameter_min': 368.5870120303,
      'estimated_diameter_max': 824.1856145234}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 18:22',
      'epoch_date_close_approach': 1704219720000,
      'relative_velocity': {'kilometers_per_second': '18.9936426332',
       'kilometers_per_hour': '68377.1134793652',
       'miles_per_hour': '42486.8792061089'},
      'miss_distance': {'astronomical': '0.2012574006',
       'lunar': '78.2891288334',
       'kilometers': '30107678.451496722',
       'miles': '18708043.8862378836'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3842680?api_key=s4R5sbtXMJtr68tnL8U9a4CszFapSMReUniEB7Wo'},
    'id': '3842680',
    'neo_reference_id': '3842680',
    'name': '(2019 KK5)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3842680',
    'absolute_magnitude_h': 22.79,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0735453089,
      'estimated_diameter_max': 0.1644523102},
     'meters': {'estimated_diameter_min': 73.545308935,
      'estimated_diameter_max': 164.452310205},
     'miles': {'estimated_diameter_min': 0.0456989222,
      'estimated_diameter_max': 0.1021858964},
     'feet': {'estimated_diameter_min': 241.2903913664,
      'estimated_diameter_max': 539.5417174129}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 21:21',
      'epoch_date_close_approach': 1704230460000,
      'relative_velocity': {'kilometers_per_second': '20.8331302779',
       'kilometers_per_hour': '74999.2690004519',
       'miles_per_hour': '46601.6291186419'},
      'miss_distance': {'astronomical': '0.0260972745',
       'lunar': '10.1518397805',
       'kilometers': '3904096.678005315',
       'miles': '2425893.185550747'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2613286?api_key=s4R5sbtXMJtr68tnL8U9a4CszFapSMReUniEB7Wo'},
    'id': '2613286',
    'neo_reference_id': '2613286',
    'name': '613286 (2005 YQ96)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2613286',
    'absolute_magnitude_h': 20.63,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.1988634532,
      'estimated_diameter_max': 0.4446721997},
     'meters': {'estimated_diameter_min': 198.8634532359,
      'estimated_diameter_max': 444.6721996757},
     'miles': {'estimated_diameter_min': 0.1235679828,
      'estimated_diameter_max': 0.2763064094},
     'feet': {'estimated_diameter_min': 652.4391719144,
      'estimated_diameter_max': 1458.8983395842}},
    'is_potentially_hazardous_asteroid': True,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 19:42',
      'epoch_date_close_approach': 1704224520000,
      'relative_velocity': {'kilometers_per_second': '15.6702896005',
       'kilometers_per_hour': '56413.0425616862',
       'miles_per_hour': '35052.8708072878'},
      'miss_distance': {'astronomical': '0.16701304',
       'lunar': '64.96807256',
       'kilometers': '24984795.0462248',
       'miles': '15524831.74571024'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2669051?api_key=s4R5sbtXMJtr68tnL8U9a4CszFapSMReUniEB7Wo'},
    'id': '2669051',
    'neo_reference_id': '2669051',
    'name': '669051 (2012 SD22)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=2669051',
    'absolute_magnitude_h': 20.08,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.2561857545,
      'estimated_diameter_max': 0.5728487619},
     'meters': {'estimated_diameter_min': 256.1857544793,
      'estimated_diameter_max': 572.8487618827},
     'miles': {'estimated_diameter_min': 0.1591863984,
      'estimated_diameter_max': 0.355951608},
     'feet': {'estimated_diameter_min': 840.5044707257,
      'estimated_diameter_max': 1879.4251319352}},
    'is_potentially_hazardous_asteroid': True,
    'close_approach_data': [{'close_approach_date': '2024-01-02',
      'close_approach_date_full': '2024-Jan-02 13:50',
      'epoch_date_close_approach': 1704203400000,
      'relative_velocity': {'kilometers_per_second': '11.0227939149',
       'kilometers_per_hour': '39682.0580935237',
       'miles_per_hour': '24656.8877081676'},
      'miss_distance': {'astronomical': '0.1644228604',
       'lunar': '63.9604926956',
       'kilometers': '24597309.695147348',
       'miles': '15284059.5133074824'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False}],
  '2024-01-01': [{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3724393?api_key=s4R5sbtXMJtr68tnL8U9a4CszFapSMReUniEB7Wo'},
    'id': '3724393',
    'neo_reference_id': '3724393',
    'name': '(2015 OD22)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3724393',
    'absolute_magnitude_h': 21.21,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.152249185,
      'estimated_diameter_max': 0.3404395273},
     'meters': {'estimated_diameter_min': 152.249185036,
      'estimated_diameter_max': 340.4395272595},
     'miles': {'estimated_diameter_min': 0.0946032284,
      'estimated_diameter_max': 0.2115392495},
     'feet': {'estimated_diameter_min': 499.5052162336,
      'estimated_diameter_max': 1116.9276186141}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2024-01-01',
      'close_approach_date_full': '2024-Jan-01 11:58',
      'epoch_date_close_approach': 1704110280000,
      'relative_velocity': {'kilometers_per_second': '25.3931645932',
       'kilometers_per_hour': '91415.3925356518',
       'miles_per_hour': '56801.969878611'},
      'miss_distance': {'astronomical': '0.4372881787',
       'lunar': '170.1051015143',
       'kilometers': '65417380.109699369',
       'miles': '40648475.1053305322'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3797695?api_key=s4R5sbtXMJtr68tnL8U9a4CszFapSMReUniEB7Wo'},
    'id': '3797695',
    'neo_reference_id': '3797695',
    'name': '(2018 BA)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3797695',
    'absolute_magnitude_h': 25.0,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.02658,
      'estimated_diameter_max': 0.0594346868},
     'meters': {'estimated_diameter_min': 26.58,
      'estimated_diameter_max': 59.4346868419},
     'miles': {'estimated_diameter_min': 0.0165160412,
      'estimated_diameter_max': 0.0369309908},
     'feet': {'estimated_diameter_min': 87.2047272,
      'estimated_diameter_max': 194.9956979785}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2024-01-01',
      'close_approach_date_full': '2024-Jan-01 08:13',
      'epoch_date_close_approach': 1704096780000,
      'relative_velocity': {'kilometers_per_second': '16.7051869184',
       'kilometers_per_hour': '60138.6729062958',
       'miles_per_hour': '37367.8326178036'},
      'miss_distance': {'astronomical': '0.3961064439',
       'lunar': '154.0854066771',
       'kilometers': '59256680.300714493',
       'miles': '36820393.7545182834'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False},
   {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3986699?api_key=s4R5sbtXMJtr68tnL8U9a4CszFapSMReUniEB7Wo'},
    'id': '3986699',
    'neo_reference_id': '3986699',
    'name': '(2020 BC)',
    'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3986699',
    'absolute_magnitude_h': 26.2,
    'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0152951935,
      'estimated_diameter_max': 0.0342010925},
     'meters': {'estimated_diameter_min': 15.2951935344,
      'estimated_diameter_max': 34.201092472},
     'miles': {'estimated_diameter_min': 0.0095039897,
      'estimated_diameter_max': 0.021251567},
     'feet': {'estimated_diameter_min': 50.1810827555,
      'estimated_diameter_max': 112.2083122258}},
    'is_potentially_hazardous_asteroid': False,
    'close_approach_data': [{'close_approach_date': '2024-01-01',
      'close_approach_date_full': '2024-Jan-01 16:14',
      'epoch_date_close_approach': 1704125640000,
      'relative_velocity': {'kilometers_per_second': '8.3141771772',
       'kilometers_per_hour': '29931.0378379052',
       'miles_per_hour': '18597.9829276695'},
      'miss_distance': {'astronomical': '0.1675870266',
       'lunar': '65.1913533474',
       'kilometers': '25070662.218993342',
       'miles': '15578187.1327464396'},
      'orbiting_body': 'Earth'}],
    'is_sentry_object': False}],

In [4]:
import requests

API_KEY = "n8kLzUsjid5jgJ5ce3vqDuOtnybSmCqChn3tB9R4"

url = "https://api.nasa.gov/neo/rest/v1/feed"
params = {
    "start_date": "2024-01-01",
    "end_date": "2024-01-03",
    "api_key": API_KEY
}

response = requests.get(url, params=params)
response

In [1]:
!pip install requests

Requirement already satisfied: requests in C:\Users\Manju\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Manju\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Manju\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\Manju\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\Manju\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests) (2026.7.22)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
import requests

start_date = "2024-01-01"
end_date = "2024-01-03"
api_key = "s4R5sbtXMJtr68tnL8U9a4CszFapSMReUniEB7Wo"

url = f"https://api.nasa.gov/neo/rest/v1/feed?start_date={start_date}&end_date={end_date}&api_key={api_key}"

response = requests.get(url)
data = response.json()

In [12]:
records = []

for date,asteroids in data['near_earth_objects'].items():
    for asteroid in asteroids:
        records.append(dict(name = asteroid['name'],
             id = asteroid['id'],
             magnitude = asteroid['absolute_magnitude_h'],
             date = asteroid['close_approach_data'][0]['close_approach_date'],
             orbiting_body = asteroid['close_approach_data'][0]['orbiting_body'],
             neo_id = asteroid['neo_reference_id'],
             astronomical =asteroid['close_approach_data'][0]['miss_distance']['astronomical']))
records

[{'name': '415949 (2001 XY10)',
  'id': '2415949',
  'magnitude': 19.37,
  'date': '2024-01-02',
  'orbiting_body': 'Earth',
  'neo_id': '2415949',
  'astronomical': '0.3372535274'},
 {'name': '(2003 SR84)',
  'id': '3160747',
  'magnitude': 26.0,
  'date': '2024-01-02',
  'orbiting_body': 'Earth',
  'neo_id': '3160747',
  'astronomical': '0.1323425924'},
 {'name': '(2005 YQ96)',
  'id': '3309828',
  'magnitude': 20.62,
  'date': '2024-01-02',
  'orbiting_body': 'Earth',
  'neo_id': '3309828',
  'astronomical': '0.1670126223'},
 {'name': '(2009 HC21)',
  'id': '3457842',
  'magnitude': 22.1,
  'date': '2024-01-02',
  'orbiting_body': 'Earth',
  'neo_id': '3457842',
  'astronomical': '0.4920511029'},
 {'name': '(2010 XA11)',
  'id': '3553062',
  'magnitude': 26.1,
  'date': '2024-01-02',
  'orbiting_body': 'Earth',
  'neo_id': '3553062',
  'astronomical': '0.2358022486'},
 {'name': '(2011 YP10)',
  'id': '3591616',
  'magnitude': 23.94,
  'date': '2024-01-02',
  'orbiting_body': 'Earth',
  'neo_id': '3591616',
  'astronomical': '0.0704899554'},
 {'name': '(2012 SD22)',
  'id': '3608936',
  'magnitude': 20.05,
  'date': '2024-01-02',
  'orbiting_body': 'Earth',
  'neo_id': '3608936',
  'astronomical': '0.1644228854'},
 {'name': '(2017 YD8)',
  'id': '3795154',
  'magnitude': 21.87,
  'date': '2024-01-02',
  'orbiting_body': 'Earth',
  'neo_id': '3795154',
  'astronomical': '0.2012574006'},
 {'name': '(2019 KK5)',
  'id': '3842680',
  'magnitude': 22.79,
  'date': '2024-01-02',
  'orbiting_body': 'Earth',
  'neo_id': '3842680',
  'astronomical': '0.0260972745'},
 {'name': '613286 (2005 YQ96)',
  'id': '2613286',
  'magnitude': 20.63,
  'date': '2024-01-02',
  'orbiting_body': 'Earth',
  'neo_id': '2613286',
  'astronomical': '0.16701304'},
 {'name': '669051 (2012 SD22)',
  'id': '2669051',
  'magnitude': 20.08,
  'date': '2024-01-02',
  'orbiting_body': 'Earth',
  'neo_id': '2669051',
  'astronomical': '0.1644228604'},
 {'name': '(2015 OD22)',
  'id': '3724393',
  'magnitude': 21.21,
  'date': '2024-01-01',
  'orbiting_body': 'Earth',
  'neo_id': '3724393',
  'astronomical': '0.4372881787'},
 {'name': '(2018 BA)',
  'id': '3797695',
  'magnitude': 25.0,
  'date': '2024-01-01',
  'orbiting_body': 'Earth',
  'neo_id': '3797695',
  'astronomical': '0.3961064439'},
 {'name': '(2020 BC)',
  'id': '3986699',
  'magnitude': 26.2,
  'date': '2024-01-01',
  'orbiting_body': 'Earth',
  'neo_id': '3986699',
  'astronomical': '0.1675870266'},
 {'name': '(2003 JV14)',
  'id': '3154493',
  'magnitude': 21.39,
  'date': '2024-01-03',
  'orbiting_body': 'Earth',
  'neo_id': '3154493',
  'astronomical': '0.2621610014'},
 {'name': '(2011 YE40)',
  'id': '3591759',
  'magnitude': 25.2,
  'date': '2024-01-03',
  'orbiting_body': 'Earth',
  'neo_id': '3591759',
  'astronomical': '0.1185645923'},
 {'name': '(2012 AB11)',
  'id': '3595775',
  'magnitude': 22.32,
  'date': '2024-01-03',
  'orbiting_body': 'Earth',
  'neo_id': '3595775',
  'astronomical': '0.2870697327'},
 {'name': '(2012 LJ2)',
  'id': '3605578',
  'magnitude': 21.7,
  'date': '2024-01-03',
  'orbiting_body': 'Earth',
  'neo_id': '3605578',
  'astronomical': '0.4856779711'},
 {'name': '(2013 NT11)',
  'id': '3645001',
  'magnitude': 19.49,
  'date': '2024-01-03',
  'orbiting_body': 'Earth',
  'neo_id': '3645001',
  'astronomical': '0.3878716833'},
 {'name': '(2016 GZ215)',
  'id': '3751529',
  'magnitude': 21.08,
  'date': '2024-01-03',
  'orbiting_body': 'Earth',
  'neo_id': '3751529',
  'astronomical': '0.3169592421'},
 {'name': '(2017 UJ2)',
  'id': '3787600',
  'magnitude': 30.9,
  'date': '2024-01-03',
  'orbiting_body': 'Earth',
  'neo_id': '3787600',
  'astronomical': '0.2789034507'},
 {'name': '(2017 WQ1)',
  'id': '3789479',
  'magnitude': 24.98,
  'date': '2024-01-03',
  'orbiting_body': 'Earth',
  'neo_id': '3789479',
  'astronomical': '0.3928589898'},
 {'name': '(2019 AE3)',
  'id': '3837605',
  'magnitude': 27.4,
  'date': '2024-01-03',
  'orbiting_body': 'Earth',
  'neo_id': '3837605',
  'astronomical': '0.219831404'},
 {'name': '(2020 BG1)',
  'id': '3986746',
  'magnitude': 22.08,
  'date': '2024-01-03',
  'orbiting_body': 'Earth',
  'neo_id': '3986746',
  'astronomical': '0.4392947647'},
 {'name': '668499 (2012 AB11)',
  'id': '2668499',
  'magnitude': 22.32,
  'date': '2024-01-03',
  'orbiting_body': 'Earth',
  'neo_id': '2668499',
  'astronomical': '0.2870697328'}]

In [13]:
!pip install pymysql

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
t = (1,2,3,4,5)
t1= (4,5,6,7,8)
value = t + t1
print(value)

(1, 2, 3, 4, 5, 4, 5, 6, 7, 8)

In [7]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\Manju\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Manju\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Manju\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Manju\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\Manju\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
data = {
    "Name": ["Asha", "Rahul", "Meena", "Arun", "Sara", "Vikram"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Age": [23, 28, 25, 32, 26, 30],
    "Salary": [45000, 52000, 60000, 75000, 48000, 68000],
    "City": ["Chennai", "Bangalore", "Chennai", "Mumbai", "Bangalore", "Chennai"]
}
df = pd.DataFrame(data)
(df)

     Name Department  Age  Salary       City
0    Asha         IT   23   45000    Chennai
1   Rahul         HR   28   52000  Bangalore
2   Meena         IT   25   60000    Chennai
3    Arun    Finance   32   75000     Mumbai
4    Sara         HR   26   48000  Bangalore
5  Vikram         IT   30   68000    Chennai

In [3]:
df['Department']

0         IT
1         HR
2         IT
3    Finance
4         HR
5         IT
Name: Department, dtype: str

In [4]:
df.columns

Index(['Name', 'Department', 'Age', 'Salary', 'City'], dtype='str')

In [8]:
df.dtypes

Name            str
Department      str
Age           int64
Salary        int64
City            str
dtype: object

In [2]:
import json

In [5]:
student = {"name":"Arun","age":28,"course":"Ds","mark":[70,96,88,74]}
with open ("student.json","w")as file:
    json.dump(student,file)

In [10]:
with open ("student.json","r")as file:
    student = json.load(file)
print(student)
type(student)

{'name': 'Arun', 'age': 28, 'course': 'Ds', 'mark': [70, 96, 88, 74]}

dict

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Department  6 non-null      str
 2   Age         6 non-null      int64
 3   Salary      6 non-null      int64
 4   City        6 non-null      str
dtypes: int64(2), str(3)
memory usage: 372.0 bytes

In [6]:
students = {
    "name": ["Arun","Deepika","Viji","Sweetha","Arjun"],
    "age": [15,20,22,18,12],
    "course": ["DS","AI","Python","Statistic","SQL"],
    "marks": [79,83,65,90,88]
}
df = pd.DataFrame(students)
df

      name  age     course  marks
0     Arun   15         DS     79
1  Deepika   20         AI     83
2     Viji   22     Python     65
3  Sweetha   18  Statistic     90
4    Arjun   12        SQL     88

In [4]:
import pandas as pd

In [9]:
df.info()
df.describe().head(3).shape

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      str
 1   age     5 non-null      int64
 2   course  5 non-null      str
 3   marks   5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

(3, 2)

In [10]:
df["marks"]

0    79
1    83
2    65
3    90
4    88
Name: marks, dtype: int64

In [16]:
df[["name","course","marks"]].head(3).tail(2)

      name  course  marks
1  Deepika      AI     83
2     Viji  Python     65

In [20]:
def score(marks):
    if marks >= 40:
        return True
    else:
        return False
df["pass"] = df["marks"].apply(score)
df

      name  age     course  marks  pass
0     Arun   15         DS     79  True
1  Deepika   20         AI     83  True
2     Viji   22     Python     65  True
3  Sweetha   18  Statistic     90  True
4    Arjun   12        SQL     88  True

In [22]:
df.loc[df["marks"]>70,["name","marks"]]

      name  marks
0     Arun     79
1  Deepika     83
3  Sweetha     90
4    Arjun     88

In [24]:
df.loc[df["age"]<20,["name","age"]]

      name  age
0     Arun   15
3  Sweetha   18
4    Arjun   12

In [30]:
df.iloc[0:3,0:2]

      name  age
0     Arun   15
1  Deepika   20
2     Viji   22

In [33]:
df.iloc[2:5,1:4]

   age     course  marks
2   22     Python     65
3   18  Statistic     90
4   12        SQL     88

In [37]:
df.sort_values(["course","marks"],ascending=[True,False])

      name  age     course  marks  pass
1  Deepika   20         AI     83  True
0     Arun   15         DS     79  True
2     Viji   22     Python     65  True
4    Arjun   12        SQL     88  True
3  Sweetha   18  Statistic     90  True

In [ ]:
df[(df["marks"]>=60)&(df["marks"]<25)]
df

      name  age     course  marks  pass
0     Arun   15         DS     79  True
1  Deepika   20         AI     83  True
2     Viji   22     Python     65  True
3  Sweetha   18  Statistic     90  True
4    Arjun   12        SQL     88  True

In [45]:
df[(df["course"]=="Python")|(df["course"]=="SQL")]

    name  age  course  marks  pass
2   Viji   22  Python     65  True
4  Arjun   12     SQL     88  True

In [ ]:
import requests
import pandas as pd
from datetime import datetime

url = "https://earthquake.usgs.gov/fdsnws/event/1/query"
all_records = []
start_year = datetime.now().year - 5 # last 5 years
end_year = datetime.now().year

for year in range(start_year,end_year+1):
    for month in range(1,13):
        if year == 2026 and month>9:
            break

In [3]:
start_year = 2021
end_year = 2026
for year in range(start_year,end_year+1):
    for month in range(1,13):
        if year == 2026 and month>9:
            break
print(start_year)
print(end_year)

2021
2026